name: 'Create Branch'
description: 'Creates a branch'
author: 'Peter Grainger (peter@grainger)'
branding:
  icon: 'git-branch'
  color: 'green'
inputs:
  branch:
    description: 'The branch to create (or update if it already exists via a fast-forward)'
    default: 'release-candidate'
  sha:
    description: 'The SHA1 value for the branch reference. If omitted the action uses the event SHA.'
outputs:
  created:
    description: 'Boolean value representing whether the branch reference was successfully created or updated to the requested SHA.'
runs:
  using: 'node20'
  main: 'dist/index.js'
